### ISSUE TITLE
Can't enter demographic data

### ISSUE THREAD

**Issue by cyberhobo** [nevada-bicycle-coalition/RenoTracks_iOS#17]
This came in from Rob De Haan via email:

    The app on my iPhone 5S won't allow me enter my age, sex, ethnicity, etc... 
    When I tap on the field the screen goes dim but then doesn't show a keypad so 
    I can enter the info. I've power cycled my phone and quit and re-opened the app 
    several times.

     I'm tracking my bike-to-work week miles so I want to send accurate data!

**Comment by Boneill3** [comment]
I have a fix, just doing some additional cleanup and it will be ready to go!
