### ISSUE TITLE
Unknown column 'south_bound' in 'field list'

### ISSUE THREAD

**Issue by Boneill3** [nevada-bicycle-coalition/RenoTracks_iOS#19]
Seeing the below message in http://rtstage.nevadabike.org/post/log.txt when posting a trip.

PHP message: DatabaseConnection::query() ERROR 1054: Unknown column 'south_bound' in 'field list': "UPDATE trip SET south_bound=39.542871788005,north_bound=39.543574870082,west_bound=-119.81715669897,east_bound=-119.8156734779,center_lat=39.543223329043,center_lng=-119.81641508844,distance_mi=0.093084362578169WHERE id='78' LIMIT 1"
PHP message: TripFactory::update() ERROR failed to update trip 78: UPDATE trip SET stop='2016-06-19 18:38:41', n_coord='41' WHERE id='78' LIMIT 1
PHP message: WARNING failed to update trip 78 stop

**Comment by cyberhobo** [comment]
Looks like the staging database schema has fallen behind - I'll try to get
it updated.

**Comment by cyberhobo** [comment]
Should be good to go now.
